[package]
name = "mutation_example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
parking_lot = { workspace = true }
rand = "0.9.2"
reratui = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
